import { useMemo } from "react";
import type { RecentItem, SleepScene, SleepSession } from "../../storage";
import { getSound } from "../../data/sounds";
import { SceneCard } from "../../components/SceneCard";

export function ProfilePage({ scenes, favorites, recent, history, onFavorite, onPlayScene }: { scenes: SleepScene[]; favorites: string[]; recent: RecentItem[]; history: SleepSession[]; onFavorite: (id: string) => void; onPlayScene: (scene: SleepScene) => void }) {
  const favoriteScenes = useMemo(() => scenes.filter((scene) => favorites.includes(scene.id)), [favorites, scenes]);
  const favoriteSounds = useMemo(() => favorites.map((id) => getSound(id)).filter((sound) => sound.id === "white" || sound.id !== "white" && getSound(sound.id).name), [favorites]);
  return <main className="v17-page v17-profile-page"><header className="v17-page-header"><div><p className="v17-eyebrow">我的</p><h1>把安静留给自己</h1><p>所有记录只保存在这台设备上</p></div></header><section className="v17-profile-summary"><span>{history.length}</span><small>次睡眠记录</small><span>{favorites.length}</span><small>个收藏</small><span>{recent.length}</span><small>条最近使用</small></section><section className="v17-library-section"><div className="v17-section-heading"><h2>我的场景</h2></div>{favoriteScenes.length ? favoriteScenes.map((scene) => <SceneCard favorite key={scene.id} onFavorite={() => onFavorite(scene.id)} onPlay={() => onPlayScene(scene)} scene={scene} />) : <p className="v17-empty-note">收藏一个场景，它会出现在这里。</p>}</section><section className="v17-library-section"><div className="v17-section-heading"><h2>收藏的声音</h2></div>{favoriteSounds.length ? favoriteSounds.map((sound) => <div className="v17-favorite-line" key={sound.id}><span>{sound.glyph}</span><strong>{sound.name}</strong></div>) : <p className="v17-empty-note">收藏一个声音，今晚可以更快开始。</p>}</section><section className="v17-library-section"><div className="v17-section-heading"><h2>睡眠记录</h2><small>最近 7 天</small></div>{history.length ? history.slice(0, 7).map((session) => <div className="v17-history-line" key={session.id}><span>{new Date(session.startedAt).toLocaleDateString("zh-CN", { month: "numeric", day: "numeric" })}</span><strong>{new Date(session.startedAt).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" })} — {session.endedAt ? new Date(session.endedAt).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" }) : "进行中"}</strong></div>) : <p className="v17-empty-note">今晚开始后，这里会留下你的安静时刻。</p>}</section><p className="v17-privacy-note">不登录、不上传、不录音。你的睡眠记录仅保存在本机。</p></main>;
}
